spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Blog
    username: root
    password: 76065633
  jpa:
    hibernate:
      ddl-auto: create
    driver-class-name: com.mysql.cj.jdbc.Driver


